name: 'Conventional Commits in PR Titles'
description: 'GitHub Action for validation PR titles match the Conventional Commits standard'
author: 'Jak Spalding'

branding:
  icon: 'git-pull-request'
  color: 'purple'

inputs:
  error_on_fail:
    description: 'Should the action cause an error if the validation fails'
    required: false
    default: 'true'

outputs:
  valid:
    description: 'true if valid, false otherwise. Useful with error_on_fail input.'

runs:
  using: node20
  main: dist/index.js
