name: Continuous Integration

on:
  pull_request:
    types:
      - synchronize
      - edited
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          fail_when_invalid: false

      - name: Print Output
        id: output
        run: |
          echo "valid=${{ steps.test-action.outputs.valid }}"
          echo "title=${{ steps.test-action.outputs.title }}"
          echo "type=${{ steps.test-action.outputs.type }}"
          echo "scope=${{ steps.test-action.outputs.scope }}"
          echo "subject=${{ steps.test-action.outputs.subject }}"
          echo "breaking_change=${{ steps.test-action.outputs.breaking_change }}"

      - name: Require Valid Title
        uses: ./
        with:
          fail_when_invalid: true
